import tomlkit
import logging
import pathlib
from typing import (
    Optional,
    Callable,
    Iterable,
    Union,
)
from tomlkit.exceptions import TOMLKitError
from tomlkit.items import Table, Array, Item
from tomlkit.toml_file import TOMLFile
from tomlkit.toml_document import TOMLDocument

DEFAULT_EXTENSIONS = [
    'dactylomancy.config.commands',
    'dactylomancy.extensions.commands',
    'dactylomancy.text.commands',
    'dactylomancy.presence.commands',
]

DEFAULT_SANITISED_VARIABLES = [
    tomlkit.array(['core', 'token']),  # type: ignore[arg-type]
    tomlkit.array(['core', 'user']),  # type: ignore[arg-type]
]

TABLE_INDENTATION = 4

CONFIG_TITLE = tomlkit.string('Dactylomancy Config')


class DactylomancyTable:

    def __init__(self, table: Table, write_out: Callable[[], None]) -> None:
        self.table = table
        self.write_out = write_out

    def __getitem__(self, key: str):
        return self.table[key]

    def __setitem__(self, key: str, value: Union[Item | Table]):
        self.table[key] = value
        self.write_out()

    def __delitem__(self, key: str):
        del self.table[key]
        self.write_out()

    def __contains__(self, key: str):
        return key in self.table


class DactylomancyState:

    def __init__(self, file: TOMLFile, document: TOMLDocument) -> None:
        self.file = file
        self.doc = document

    def get_table(self, key: str) -> DactylomancyTable:
        if key in self.doc.keys():
            if type(self.doc[key]) is Table:
                logging.debug(f'Returning {DactylomancyTable.__name__} object for: {key}.')
                return DactylomancyTable(self.doc[key], self.write_out)  # type: ignore[arg-type]
            else:
                raise ValueError(f'key: {key} found but does not correspond to a table')
        else:
            logging.info(f'Creating new config table for: {key}.')
            new_table = tomlkit.table()
            new_table.indent(TABLE_INDENTATION)
            self.doc.append(key, new_table)
            logging.debug(f'Returning {DactylomancyTable.__name__} object for: {key}.')
            return DactylomancyTable(new_table, self.write_out)

    def write_out(self) -> None:
        logging.debug(f'Writing out to {self.file._path} with updated config.')
        self.file.write(self.doc)

    def get_sanitised_doc(self) -> TOMLDocument:
        intm = tomlkit.dumps(self.doc)
        s_doc = tomlkit.parse(intm)
        assert type(s_doc['core']) is Table
        assert type(s_doc['core']['sanitisations']) is Array
        for s_v in s_doc['core']['sanitisations']:
            tmp: dict = s_doc
            l_s_v = list(s_v)
            for subkey in l_s_v[:-1]:
                tmp = tmp[subkey]
            tmp[l_s_v[-1]] = tomlkit.string('REDACTED_DURING_DOCUMENT_SANITATION')
        return s_doc

    def set_sanitised_variable(self, keys: Iterable[str]):
        assert type(self.doc['core']) is Table
        s_arr = self.doc['core']['sanitisations']
        assert type(s_arr) is Array
        s_arr.append(tomlkit.array(list(keys)))  # type: ignore[arg-type]
        logging.debug(f'{'.'.join(keys)} added to sanitised variables.')

    def __getitem__(self, key: str):
        return self.doc[key]

    def __setitem__(self, key: str, value: Union[Item | Table]):
        self.doc[key] = value
        logging.debug(f'Setting {key} to {value} in main config.')
        self.write_out()

    def __delitem__(self, key: str):
        del self.doc[key]
        logging.debug(f'Deleting {key} from main config.')
        self.write_out()

    def __contains__(self, key: str):
        return key in self.doc


def create_config_doc(token: str = "", snowflake: int = 0) -> TOMLDocument:

    doc = TOMLDocument()
    doc.add(tomlkit.comment(f'Autogenerated file by {__file__}'))
    doc.append('title', CONFIG_TITLE)
    core_table = tomlkit.table()
    core_table.indent(TABLE_INDENTATION)
    core_table.comment('Table of the core configuration options')
    # Add the token to the core table
    core_table.append('token', token)
    # Add a placeholder for the user snowflake
    core_table.append('user', snowflake)
    # Add a placeholder for the command prefix
    prefix = tomlkit.string('')
    prefix.comment('Prefix attached before all applications commands to help multiple bot users')
    # Add the flag to sync commands on initialisation
    core_table.append('prefix', prefix)
    sync_on_init = tomlkit.boolean('true')
    sync_on_init.comment('If the bot should sync commands when next initialised, will be toggled off')
    core_table.append('sync_on_init', sync_on_init)
    # Create the default arrays of extensions, and external dependencies to be loaded
    extensions = tomlkit.array(DEFAULT_EXTENSIONS)  # type: ignore[arg-type]
    extensions.multiline(True)
    extensions.comment('A list of extensions to be imported')
    core_table.append('extensions', extensions)
    dependencies = tomlkit.array()
    dependencies.multiline(True)
    dependencies.comment('List of additional packages to be loaded via pip')
    core_table.append('dependencies', dependencies)
    # Create the list of private variables to be removed when sanitising the configuration
    sanitisations = tomlkit.array(DEFAULT_SANITISED_VARIABLES)  # type: ignore[arg-type]
    sanitisations.multiline(True)
    sanitisations.comment('Private variables to be removed when sanitising the configuration')
    core_table.append('sanitisations', sanitisations)
    doc.append('core', core_table)
    return doc


def validate_config_doc(doc: TOMLDocument) -> None:

    if doc['title'] != CONFIG_TITLE:
        raise ValueError(f'title mismatch, expected: {CONFIG_TITLE}, got: {doc['title']}')

    ground_truth = create_config_doc()
    gt_core = ground_truth['core']
    assert type(gt_core) is Table
    d_core = doc['core']
    assert type(d_core) is Table
    required_keys = set(gt_core.keys())
    present_keys = set(d_core.keys())
    if not required_keys <= present_keys:
        raise ValueError(f'key mismatch, missing: {required_keys - present_keys}')
    mismatches = []
    for key in required_keys:
        if type(d_core[key]) is not type(gt_core[key]):
            mismatches.append((key, type(d_core[key]), type(gt_core[key])))
    if mismatches:
        mismatch_str = f'type mismatch{'es' if len(mismatches) > 1 else ''} encountered: '
        for k, f, e in mismatches:
            mismatch_str += f'for {k} found: {f}, expected: {e};'
        mismatch_str = mismatch_str[:-1]
        raise ValueError(mismatch_str)


def initialise_config_state(filepath: pathlib.Path, token: Optional[str], snowflake: Optional[int]) -> DactylomancyState:

    if not filepath.exists():
        if token is None:
            logging.critical('No token given, and no config file exists, exiting.')
            print('please provide a bot token or config file')
            exit(1)
        elif snowflake is None:
            logging.critical('No user-id given, and no config file exists, exiting.')
            print('please provide a user-id or config file')
            exit(1)
        else:
            config_file = TOMLFile(filepath)
            logging.info(f'Creating new config file: {filepath}')
            config_doc = create_config_doc(token, snowflake)
            config_file.write(config_doc)
    elif filepath.exists() and not filepath.is_file():
        logging.critical(f'{filepath} is a directory, exiting.')
        print(f'please provide a complete config file path, {filepath} is a directory or folder')
        exit(1)
    else:
        config_file = TOMLFile(filepath)
        logging.debug(f'Attempting to parse {filepath} as config file.')
        try:
            config_doc = config_file.read()
            validate_config_doc(config_doc)
        except TOMLKitError as exc:
            logging.critical(f'Error while parsing {filepath}, exiting.', exc_info=exc)
            print(f'config file {filepath} could not be parsed, please check the file is correct')
            exit(1)
        except ValueError as exc:
            logging.critical(f'Error while validating {filepath}, exiting.', exc_info=exc)
            print(f'config file {filepath} could not be validated, please check the file is correct')
            exit(1)
        logging.debug(f'Parsed and validated {filepath} as a toml file.')

    return DactylomancyState(config_file, config_doc)
