# This is a barebones config.

title = "Basic Example"

[features]
cogs = [
    "speech.basics",
    "presence.basics",
]

[discord]
token = <bot-token>
# The token of the bot to be used as proxy.
scribe = <snowflake-id>
# The snowflake id of the account that will be scribing for the proxy,
# i.e. the standard user account that will type the messages.